name: nix flake check

on:
  push:

jobs:
  check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            experimental-features = no-url-literals
      - uses: cachix/cachix-action@v10
        with:
          name: ngi
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix flake check --print-build-logs
