[tool.poetry]
name = "pretalx-service"
version = "0.1.0"
description = "Pretalx service"
authors = [] # see meta.maintainers in pkgs/pretalx/default.nix

[tool.poetry.dependencies]
python = ">=3.9,<3.12"
pretalx = "2.3.2"

[tool.poetry.group.plugins]
optional = true

[tool.poetry.group.plugins.dependencies]
pretalx-downstream = "*"
pretalx-media-ccc-de = "*"
pretalx-orcid = "*"
pretalx-pages = "*"
pretalx-public-voting = "*"
pretalx-venueless = "*"
pretalx-vimeo = "*"
pretalx-youtube = "*"

[tool.poetry.group.mysql]
optional = true

[tool.poetry.group.mysql.dependencies]
mysqlclient = "*"

[tool.poetry.group.postgresql]
optional = true

[tool.poetry.group.postgresql.dependencies]
psycopg2-binary = "*"

[tool.poetry.group.redis]
optional = true

[tool.poetry.group.redis.dependencies]
django-redis = "*"

[tool.poetry.group.test]
optional = true

[tool.poetry.group.test.dependencies]
Faker = "*"
freezegun = "*"

[tool.poetry.scripts]
pretalx = "pretalx_service:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
